apiVersion: apps/v1
kind: Deployment
metadata:
  name: firecrawl-api
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: playwright-service
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-html-to-md-service
spec:
  replicas: 1